apiVersion: v1
kind: pod
metadata:
  name: webserver
spec: 
    containers:
    - name: webserver
      image: nginx
      ports: 
      - containersPort:80
    - name: webwatcher
      image: afakharany/watcher:latest
